@localhost=localhost:4004/odata/v4/main
@id=96cfa9cb-cb6d-4141-99e6-32bf45209585

GET http://{{localhost}}/Customers
Content-Type: application/json

###

POST http://{{localhost}}/Customers
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "Mateus",
    "lastName": "Rodrigues",
    "email": "mateus.silva@numenit.com"
}

###

DELETE http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "John"
}

###

PATCH http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "John"
}

###

GET http://{{localhost}}/Customers?$filter=endswith(firstName,'-6648544') and email ne 'email-6648544'
Content-Type: application/json

###

# Buscando dados com $search(pesquisar)
GET http://{{localhost}}/Customers?$search=firstName2
Content-Type: application/json

###

# Ordenando dados com $orderby
GET http://{{localhost}}/Customers?$orderby=firstName desc,lastName
Content-Type: application/json