@localhost=localhost:4004/odata/v4/main
@id=bc3bee27-f54d-4b45-9b66-541dd5f89573
@customerId=96cfa9cb-cb6d-4141-99e6-32bf45209585
@productId=bca6b19d-7bd7-48c2-8447-595a29c418cb

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "fe70f313-b7de-47cb-a9a6-8b584a200a1e",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "3c0cf492-c56c-4b86-8951-6b1388dde401",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modfiedBy": "teste"
}

###

# Buscar todos os pedidos maiores ou iguais a 2 milhões
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount ge 200000

###

# Buscar todos os pedidos menores ou iguais a 200k
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200000

###

# Expandindo os items, produtos e customers
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$expand=items($expand=product),customer

###

# Expandindo os items, produtos e customers
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer